import { Config } from "effect"

// Arcanea dual-env support: ARCANEA_* takes priority, OPENCODE_* as fallback
function env(arcanea: string, opencode: string): string | undefined {
  return process.env[arcanea] ?? process.env[opencode]
}

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function truthyDual(arcanea: string, opencode: string) {
  return truthy(arcanea) || truthy(opencode)
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function falsyDual(arcanea: string, opencode: string) {
  return falsy(arcanea) || falsy(opencode)
}

export namespace Flag {
  export const OPENCODE_AUTO_SHARE = truthyDual("ARCANEA_AUTO_SHARE", "OPENCODE_AUTO_SHARE")
  export const OPENCODE_GIT_BASH_PATH = env("ARCANEA_GIT_BASH_PATH", "OPENCODE_GIT_BASH_PATH")
  export const OPENCODE_CONFIG = env("ARCANEA_CONFIG", "OPENCODE_CONFIG")
  export declare const OPENCODE_TUI_CONFIG: string | undefined
  export declare const OPENCODE_CONFIG_DIR: string | undefined
  export const OPENCODE_CONFIG_CONTENT = env("ARCANEA_CONFIG_CONTENT", "OPENCODE_CONFIG_CONTENT")
  export const OPENCODE_DISABLE_AUTOUPDATE = truthyDual("ARCANEA_DISABLE_AUTOUPDATE", "OPENCODE_DISABLE_AUTOUPDATE")
  export const OPENCODE_ALWAYS_NOTIFY_UPDATE = truthy("OPENCODE_ALWAYS_NOTIFY_UPDATE")
  export const OPENCODE_DISABLE_PRUNE = truthyDual("ARCANEA_DISABLE_PRUNE", "OPENCODE_DISABLE_PRUNE")
  export const OPENCODE_DISABLE_TERMINAL_TITLE = truthyDual("ARCANEA_DISABLE_TERMINAL_TITLE", "OPENCODE_DISABLE_TERMINAL_TITLE")
  export const OPENCODE_PERMISSION = env("ARCANEA_PERMISSION", "OPENCODE_PERMISSION")
  export const OPENCODE_DISABLE_DEFAULT_PLUGINS = truthyDual("ARCANEA_DISABLE_DEFAULT_PLUGINS", "OPENCODE_DISABLE_DEFAULT_PLUGINS")
  export const OPENCODE_DISABLE_LSP_DOWNLOAD = truthyDual("ARCANEA_DISABLE_LSP_DOWNLOAD", "OPENCODE_DISABLE_LSP_DOWNLOAD")
  export const OPENCODE_ENABLE_EXPERIMENTAL_MODELS = truthyDual("ARCANEA_ENABLE_EXPERIMENTAL_MODELS", "OPENCODE_ENABLE_EXPERIMENTAL_MODELS")
  export const OPENCODE_DISABLE_AUTOCOMPACT = truthyDual("ARCANEA_DISABLE_AUTOCOMPACT", "OPENCODE_DISABLE_AUTOCOMPACT")
  export const OPENCODE_DISABLE_MODELS_FETCH = truthyDual("ARCANEA_DISABLE_MODELS_FETCH", "OPENCODE_DISABLE_MODELS_FETCH")
  export const OPENCODE_DISABLE_CLAUDE_CODE = truthyDual("ARCANEA_DISABLE_CLAUDE_CODE", "OPENCODE_DISABLE_CLAUDE_CODE")
  export const OPENCODE_DISABLE_CLAUDE_CODE_PROMPT =
    OPENCODE_DISABLE_CLAUDE_CODE || truthyDual("ARCANEA_DISABLE_CLAUDE_CODE_PROMPT", "OPENCODE_DISABLE_CLAUDE_CODE_PROMPT")
  export const OPENCODE_DISABLE_CLAUDE_CODE_SKILLS =
    OPENCODE_DISABLE_CLAUDE_CODE || truthyDual("ARCANEA_DISABLE_CLAUDE_CODE_SKILLS", "OPENCODE_DISABLE_CLAUDE_CODE_SKILLS")
  export const OPENCODE_DISABLE_EXTERNAL_SKILLS =
    OPENCODE_DISABLE_CLAUDE_CODE_SKILLS || truthyDual("ARCANEA_DISABLE_EXTERNAL_SKILLS", "OPENCODE_DISABLE_EXTERNAL_SKILLS")
  export declare const OPENCODE_DISABLE_PROJECT_CONFIG: boolean
  export const OPENCODE_FAKE_VCS = env("ARCANEA_FAKE_VCS", "OPENCODE_FAKE_VCS")
  export declare const OPENCODE_CLIENT: string
  export const OPENCODE_SERVER_PASSWORD = env("ARCANEA_SERVER_PASSWORD", "OPENCODE_SERVER_PASSWORD")
  export const OPENCODE_SERVER_USERNAME = env("ARCANEA_SERVER_USERNAME", "OPENCODE_SERVER_USERNAME")
  export const OPENCODE_ENABLE_QUESTION_TOOL = truthyDual("ARCANEA_ENABLE_QUESTION_TOOL", "OPENCODE_ENABLE_QUESTION_TOOL")

  // Experimental
  export const OPENCODE_EXPERIMENTAL = truthyDual("ARCANEA_EXPERIMENTAL", "OPENCODE_EXPERIMENTAL")
  export const OPENCODE_EXPERIMENTAL_FILEWATCHER = Config.boolean("OPENCODE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  )
  export const OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER = Config.boolean(
    "OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER",
  ).pipe(Config.withDefault(false))
  export const OPENCODE_EXPERIMENTAL_ICON_DISCOVERY =
    OPENCODE_EXPERIMENTAL || truthyDual("ARCANEA_EXPERIMENTAL_ICON_DISCOVERY", "OPENCODE_EXPERIMENTAL_ICON_DISCOVERY")

  const copy = env("ARCANEA_EXPERIMENTAL_DISABLE_COPY_ON_SELECT", "OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
  export const OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT =
    copy === undefined ? process.platform === "win32" : truthyDual("ARCANEA_EXPERIMENTAL_DISABLE_COPY_ON_SELECT", "OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
  export const OPENCODE_ENABLE_EXA =
    truthyDual("ARCANEA_ENABLE_EXA", "OPENCODE_ENABLE_EXA") || OPENCODE_EXPERIMENTAL || truthyDual("ARCANEA_EXPERIMENTAL_EXA", "OPENCODE_EXPERIMENTAL_EXA")
  export const OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = number("ARCANEA_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS") ?? number("OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS")
  export const OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX = number("ARCANEA_EXPERIMENTAL_OUTPUT_TOKEN_MAX") ?? number("OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX")
  export const OPENCODE_EXPERIMENTAL_OXFMT = OPENCODE_EXPERIMENTAL || truthyDual("ARCANEA_EXPERIMENTAL_OXFMT", "OPENCODE_EXPERIMENTAL_OXFMT")
  export const OPENCODE_EXPERIMENTAL_LSP_TY = truthyDual("ARCANEA_EXPERIMENTAL_LSP_TY", "OPENCODE_EXPERIMENTAL_LSP_TY")
  export const OPENCODE_EXPERIMENTAL_LSP_TOOL = OPENCODE_EXPERIMENTAL || truthyDual("ARCANEA_EXPERIMENTAL_LSP_TOOL", "OPENCODE_EXPERIMENTAL_LSP_TOOL")
  export const OPENCODE_DISABLE_FILETIME_CHECK = Config.boolean("OPENCODE_DISABLE_FILETIME_CHECK").pipe(
    Config.withDefault(false),
  )
  export const OPENCODE_EXPERIMENTAL_PLAN_MODE = OPENCODE_EXPERIMENTAL || truthyDual("ARCANEA_EXPERIMENTAL_PLAN_MODE", "OPENCODE_EXPERIMENTAL_PLAN_MODE")
  export const OPENCODE_EXPERIMENTAL_WORKSPACES = OPENCODE_EXPERIMENTAL || truthyDual("ARCANEA_EXPERIMENTAL_WORKSPACES", "OPENCODE_EXPERIMENTAL_WORKSPACES")
  export const OPENCODE_EXPERIMENTAL_MARKDOWN = !falsyDual("ARCANEA_EXPERIMENTAL_MARKDOWN", "OPENCODE_EXPERIMENTAL_MARKDOWN")
  export const OPENCODE_MODELS_URL = env("ARCANEA_MODELS_URL", "OPENCODE_MODELS_URL")
  export const OPENCODE_MODELS_PATH = env("ARCANEA_MODELS_PATH", "OPENCODE_MODELS_PATH")
  export const OPENCODE_DISABLE_EMBEDDED_WEB_UI = truthy("OPENCODE_DISABLE_EMBEDDED_WEB_UI")
  export const OPENCODE_DB = env("ARCANEA_DB", "OPENCODE_DB")
  export const OPENCODE_DISABLE_CHANNEL_DB = truthyDual("ARCANEA_DISABLE_CHANNEL_DB", "OPENCODE_DISABLE_CHANNEL_DB")
  export const OPENCODE_SKIP_MIGRATIONS = truthyDual("ARCANEA_SKIP_MIGRATIONS", "OPENCODE_SKIP_MIGRATIONS")
  export const OPENCODE_STRICT_CONFIG_DEPS = truthyDual("ARCANEA_STRICT_CONFIG_DEPS", "OPENCODE_STRICT_CONFIG_DEPS")

  function number(key: string) {
    const value = process.env[key]
    if (!value) return undefined
    const parsed = Number(value)
    return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
  }
}

// Dynamic getter for OPENCODE_DISABLE_PROJECT_CONFIG
// Supports both ARCANEA_ and OPENCODE_ prefixes
Object.defineProperty(Flag, "OPENCODE_DISABLE_PROJECT_CONFIG", {
  get() {
    return truthyDual("ARCANEA_DISABLE_PROJECT_CONFIG", "OPENCODE_DISABLE_PROJECT_CONFIG")
  },
  enumerable: true,
  configurable: false,
})

// Dynamic getter for OPENCODE_TUI_CONFIG
Object.defineProperty(Flag, "OPENCODE_TUI_CONFIG", {
  get() {
    return process.env["ARCANEA_TUI_CONFIG"] ?? process.env["OPENCODE_TUI_CONFIG"]
  },
  enumerable: true,
  configurable: false,
})

// Dynamic getter for OPENCODE_CONFIG_DIR
Object.defineProperty(Flag, "OPENCODE_CONFIG_DIR", {
  get() {
    return process.env["ARCANEA_CONFIG_DIR"] ?? process.env["OPENCODE_CONFIG_DIR"]
  },
  enumerable: true,
  configurable: false,
})

// Dynamic getter for OPENCODE_CLIENT
Object.defineProperty(Flag, "OPENCODE_CLIENT", {
  get() {
    return process.env["ARCANEA_CLIENT"] ?? process.env["OPENCODE_CLIENT"] ?? "cli"
  },
  enumerable: true,
  configurable: false,
})
